# Generated by Django 4.2.1 on 2023-05-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0002_dayname_plan_recipeplan_plan_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='nothing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dayname',
            name='name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipeplan',
            name='meal_name',
            field=models.CharField(max_length=255),
        ),
    ]
