# Generated by Django 4.2.1 on 2023-05-09 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0002_dayname_plan_recipeplan_plan_recipes'),
    ]

    operations = [

    ]
