# Generated by Django 2.2.6 on 2023-05-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0002_dayname_plan_recipeplan_plan_recipes'),
    ]

    operations = [

    ]
