# Generated by Django 2.2.6 on 2023-05-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0003_recipe_ingredients'),
    ]

    operations = [

    ]
