# Generated by Django 2.2.6 on 2023-05-09 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0003_recipe_ingredients_recipe_preparation_method_and_more'),
        ('jedzonko', '0003_auto_20230509_1001'),
        ('jedzonko', '0006_auto_20230509_0954'),
    ]

    operations = [
    ]
