# Generated by Django 2.2.6 on 2023-05-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0008_auto_20230509_1150'),
        ('jedzonko', '0003_auto_20230509_1257'),
    ]

    operations = [
    ]
